language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew-mutt
  - brew tap --repair
env:
  - PACKAGE=mutt
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE
notifications:
    webhooks:
        - http://tg.thesharp.org:8888/travis
